name: Build & publish Star64 image
on:
  workflow_dispatch: 
    inputs:
      target:
        description: Target board
        required: true
        default: star64
        type: choice
        options: [star64]

jobs:
  build-kanso:
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.event.inputs.target }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@latest
      with:
        version: "20.1.0"

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure & build kanso
      run: |
        cmake --preset riscv64 -B build/riscv64
        cmake --build build/riscv64

    - name: Produce kernel.bin
      run: |
        riscv64-linux-gnu-objcopy \
          -O binary \
          build/riscv64/bin/kernel.elf \
          build/riscv64/bin/kernel.bin

    - name: Upload kanso artifact
      uses: actions/upload-artifact@v4
      with:
        name: kanso-${{ env.TARGET }}
        path: |
          build/riscv64/bin/kernel.elf
          build/riscv64/bin/kernel.bin
