name: Build Kernel
on:
  workflow_dispatch: 
    inputs:
      platform:
        description: Platform
        required: true
        default: riscv64
        type: choice
        options: [riscv64]

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    env:
      PLATFORM: ${{ github.event.inputs.platform }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "20.1.3"
        env: true

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure & build kanso
      run: |
        cmake --preset ${{ env.PLATFORM }} -B build/${{ env.PLATFORM }}
        cmake --build build/${{ env.PLATFORM }}

    - name: Upload kanso artifact
      uses: actions/upload-artifact@v4
      with:
        name: kanso-${{ env.PLATFORM }}
        path: |
          build/${{ env.PLATFORM }}/bin/kernel.elf
          build/${{ env.PLATFORM }}//bin/kernel.bin
          build/${{ env.PLATFORM }}//bin/kernel-test.elf
