name: Build & publish Star64 image
on:
  workflow_dispatch: 
    inputs:
      target:
        description: Target board
        required: true
        default: star64
        type: choice
        options: [star64]

jobs:
  build-kanso:
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ github.event.inputs.target }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install tool-chain & CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-riscv64-linux-gnu g++-riscv64-linux-gnu \
          binutils-riscv64-linux-gnu ninja-build python3
        # (plus the LLVM 20 + CMake 4 commands shown earlier)

    - name: Configure & build kanso
      run: |
        cmake -S kanso --preset riscv64 -B kanso/build/riscv64
        cmake --build kanso/build/riscv64

    - name: Produce kernel.bin
      run: |
        riscv64-linux-gnu-objcopy \
          -O binary \
          kanso/build/riscv64/bin/kernel.elf \
          kanso/build/riscv64/bin/kernel.bin

    - name: Upload kanso artifact
      uses: actions/upload-artifact@v4
      with:
        name: kanso-${{ env.TARGET }}
        path: |
          kanso/build/riscv64/bin/kernel.elf
          kanso/build/riscv64/bin/kernel.bin
