name: Kanso-CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: 

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      kernel: ${{ steps.filter.outputs.kernel }}
      common: ${{ steps.filter.outputs.common }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            kernel:
              - 'src/Kernel/**'
            common:
              - 'src/Common/**'

  kernel-build:
    needs: filter
    if: ${{ needs.filter.outputs.kernel == 'true' || needs.filter.outputs.common == 'true' }}
    strategy:
      matrix:
        Platform: [ "riscv64", "riscv32" ]
    uses: ./.github/workflows/kernel-build.yml
    secrets: inherit
    with:
      platform: ${{ matrix.Platform }}

  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [kernel-build]
    steps:
      - run: |
          result="${{ needs.kernel-build.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
