name: Kanso-CD
on:
  workflow_dispatch: 

jobs:
  kernel-build:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.Platforms) }}
    uses: ./.github/workflows/kernel-build.yml
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}

