name: Kernel-Build
on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORM: ${{ inputs.platform }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "20.1.3"
        env: true

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-${{ env.PLATFORM }}
        curl -LO https://github.com/qemu/qemu/raw/master/pc-bios/opensbi-${{ env.PLATFORM }}-generic-fw_dynamic.bin

    - name: Build Kernel
      run: |
        cmake --preset ${{ env.PLATFORM }} -B build/${{ env.PLATFORM }}
        cmake --build build/${{ env.PLATFORM }}

    - name: Test Kernel
      run: |
        set -euo pipefail

        (
          qemu-system-${{ env.PLATFORM }} \
            -machine virt \
            -bios opensbi-${{ env.PLATFORM }}-generic-fw_dynamic.bin
            -kernel build/${{ env.PLATFORM }}/bin/kernel-test.elf \
            -serial stdio -monitor none -nographic -no-reboot
        ) 2>&1 | tee qemu.log

        ! grep -q "\[  FAILED  ]" qemu.log

    - name: Upload Kernel binaries
      uses: actions/upload-artifact@v4
      with:
        name: kernel-${{ env.PLATFORM }}
        path: |
          build/${{ env.PLATFORM }}/bin/kernel.elf
          build/${{ env.PLATFORM }}/bin/kernel.bin
