name: Kernel-Build
on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORM: ${{ inputs.platform }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "20.1.3"
        env: true

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: 
          - ${{ env.PLATFORM }}

    - name: Configure & build kanso
      run: |
        cmake --preset ${{ env.PLATFORM }} -B build/${{ env.PLATFORM }}
        cmake --build build/${{ env.PLATFORM }}

    - name: Test
      run: echo Test

    - name: Upload kanso artifact
      uses: actions/upload-artifact@v4
      with:
        name: kanso-${{ env.PLATFORM }}
        path: |
          build/${{ env.PLATFORM }}/bin/kernel.elf
          build/${{ env.PLATFORM }}/bin/kernel.bin
