name: Kernel-Build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_TARGET_ID: ${{ inputs.releaseTargetId }}
      CROSS_COMPILE: riscv64-linux-gnu-

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Download kernel.bin artifact
      uses: actions/download-artifact@v4
      with:
        name: kernel-riscv64
        path: kanso_kernel

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-riscv64-linux-gnu g++-riscv64-linux-gnu binutils-riscv64-linux-gnu \
          device-tree-compiler bison flex libssl-dev bc \
          u-boot-tools genimage

    - name: Clone u-boot
      run: git clone https://github.com/u-boot/u-boot.git u-boot

    - name: Clone OpenSBI
      run: git clone https://github.com/riscv-software-src/opensbi.git opensbi

    - name: Clone StarFive utilities
      run: git clone https://github.com/starfive-tech/soft_3rdpart.git starfive_utils

 
